# Generated by Django 5.0.6 on 2024-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='arz',
            field=models.FloatField(default=122.2),
        ),
        migrations.AddField(
            model_name='image',
            name='blur',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='image',
            name='degree_threshold',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='image',
            name='epsilon',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='image',
            name='grid_size',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='image',
            name='methods_spline',
            field=models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High')], default=('normal', 'Normal'), max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='small_things',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='image',
            name='spline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='threshold_percentage',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='image',
            name='tool',
            field=models.FloatField(default=91.8),
        ),
    ]
