# Generated by Django 5.0.6 on 2024-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0002_image_arz_image_blur_image_degree_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='optimized_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
