# Generated by Django 5.0.6 on 2024-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0003_image_optimized_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='optimized_url',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
