# Generated by Django 5.0.6 on 2024-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0004_alter_image_optimized_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='methods_spline',
            field=models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High')], default='normal', max_length=100),
        ),
    ]
