# Generated by Django 5.0.6 on 2024-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0005_alter_image_methods_spline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='methods_spline',
            field=models.CharField(choices=[('normal', 'Normal'), ('centripetal', 'Centripetal'), ('chord', 'Chord')], default='normal', max_length=100),
        ),
    ]
