# Generated by Django 5.0.6 on 2024-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingImage', '0006_alter_image_methods_spline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='epsilon',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='image',
            name='spline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tool',
            field=models.FloatField(default=89.7),
        ),
    ]
